Add ability to define args for the just command (not the recipe).
psibi/justl.el pull request #32
Opened 2023-05-19 15:03 UTC by johnhamelink

This PR adds the ability to define flags which are passed to the just
executable itself. This is needed if, for example, a justfile requires
the `--unstable` flag.

2023-05-20 04:37 UTC, psibi requested changes
Can you look into why tests are failing ? Also, can you add a test for this ?

2023-05-20 21:12 UTC, johnhamelink commented
@psibi yes, certainly! I should have a chance have a look this week at some point.

2023-06-04 18:05 UTC, johnhamelink commented
Hi, after some more reading and understanding of the code, I realised I didn't need to reinvent the wheel - I could make use of transient's saving feature to get the results I wanted, so long as transient arguments would also be applied to the list function. I've tested it thoroughly and couldn't trigger any issue with this approach.

2023-06-08 09:56 UTC, psibi commented
@johnhamelink I guess we can close this PR then? Do you think we can document what you did via transient in the `README.org` ?

2023-06-10 12:35 UTC, johnhamelink commented
@psibi I force-pushed some changes to this repo which I think are still valid, but yes I think we should link to this section of the transient docs: https://www.gnu.org/software/emacs//manual/html_node/transient/Saving-Values.html

2023-06-11 07:04 UTC, merged

2023-06-11 07:04 UTC, psibi commented
Thank you!